#!/usr/bin/env node
"use strict";
const fs=require("fs"),path=require("path"),vm=require("vm");
const html=fs.readFileSync(path.join(__dirname,"index.html"),"utf8");
const fonts=fs.readFileSync(path.join(__dirname,"font_data.js"),"utf8");
const source=html.match(/<script>([\s\S]*)<\/script>/)[1];
let failures=0;const check=(name,value)=>{console.log((value?"ok   ":"FAIL ")+name);if(!value)failures++};
const sandbox={console,Math,Uint8ClampedArray,document:undefined};vm.createContext(sandbox);
vm.runInContext(fonts+"\n"+source+"\nconst inkBottom=(bm,bpr)=>{let row=0;for(let r=0;r<bm.length;r++){if(bm[r]!==0){const rr=Math.floor(r/bpr)+1;if(rr>row)row=rr;}}return row};\nconst baselineAligned=(()=>{const d=inkBottom(DIGIT_BITMAPS[DIGIT_CHARS.indexOf('8')],DIGIT_BPR);const h=inkBottom(HALF_BITMAPS[HALF_CHARS.indexOf('C')],HALF_BPR);return d===(DIGIT_BASELINE-HALF_BASELINE)+h;})();\nthis.EXPORTS={UI_W,UI_H,L,X_LABELS,STATUS,traceData,textBitmap,digitBitmap,halfBitmap,normalizeUnit,baselineAligned};",sandbox);
const e=sandbox.EXPORTS;
check("layout width",e.UI_W===960);check("layout height",e.UI_H===320);
check("four regions total (status+infoBar+reading+trend)",e.L.statusH+e.L.infoBarH+e.L.readingH+e.L.trendH===320);
check("reading starts 50 (v2.2 top bar)",e.L.readingY===50&&e.L.readingH===142);check("trend starts 192",e.L.trendY===192);
check("top info bar geometry",e.L.infoBarY===24&&e.L.infoBarH===26&&e.L.infoBarW===928&&e.L.infoBarX===12);
check("reverse x labels",JSON.stringify(Array.from(e.X_LABELS))===JSON.stringify(["10.00s","7.50s","5.00s","2.50s","0.00s"]));
const data=e.traceData();check("240 projected columns",data.length===240);check("deterministic non-flat trace",Math.max(...data)>Math.min(...data));
check("authentic labels",["REM","TALK","LSTN","SRQ","TRIG"].every(x=>e.STATUS.includes(x)));
check("no DMM6500 vocabulary",!["DIGITIZE","defbuffer1","No Script","DCCPL"].some(x=>html.includes(x)));
check("simulator-only preset note",html.includes("不代表面板协议"));
check("resistance unit normalizer",e.normalizeUnit("OHM")==="Ω"&&e.normalizeUnit("KOHM")==="kΩ"&&e.normalizeUnit("MOHM")==="MΩ"&&e.normalizeUnit("MVAC")==="mVAC");
check("digit unit symbols",["µ","°","Ω"].every(c=>e.digitBitmap(c)!=null));
check("half-height suffix font",["D","C","A"].every(c=>e.halfBitmap(c)!=null));
check("DC/AC baseline hits reading ink bottom",e.baselineAligned);
check("header brand and runtime",html.includes("KEITHLEY 2000")&&html.includes("demoUptime")&&html.includes("+25.0°C"));
check("no horizontal info-bar hairlines",!html.includes("L.infoBarY,960,1")&&!html.includes("L.infoBarH-1,960"));
check("row1 de-duplicated left lamps",html.includes('["REM","TALK","LSTN","SRQ","HOLD","TRIG","ERR","BUFFER","MATH","CONT"]')&&!html.includes("STATUS.forEach"));
check("row1 brand separator",html.includes("brandEnd+10")&&html.includes("Math.floor((L.statusH-12)/2)"));
check("red KEITHLEY-only badge",html.includes("ctx.fillStyle=COLORS.red;ctx.fillRect(0,0,redEnd")&&html.includes('text(ctx,head,12,0,COLORS.white)')&&html.includes('text(ctx,tail,x2000,0,COLORS.white)'));
check("rate half-height section divider",html.includes("Math.floor((L.infoBarH-12)/2)"));
check("trigger always shown",html.includes('"TRIGGER",trigX,cellY,trigOn?'));
check("row2 stats-style cells + trigger",html.includes("trigSepX")&&html.includes("TRIGGER")&&html.includes("trigDotX"));
check("green badge + divider",html.includes("ctx.fillStyle=COLORS.green;ctx.fillRect(L.badgeX")&&html.includes("L.infoBarY+L.infoBarH,960"));
check("stats widened for 7-digit (v2.1)",e.L.statsW===208&&e.L.statsNameW===60&&e.L.statsW-e.L.statsNameW>=148);
check("plot geometry (ADR-0007)",e.L.plotX===96&&e.L.plotY===218&&e.L.plotW===864&&e.L.plotH===78&&e.L.trendHeaderY===192&&e.L.trendTaskY===296);
check("left-aligned reading",e.L.readingX===12);
check("bottom band geometry",e.L.trendY===192&&e.L.trendH===128&&e.L.chartPanelY===192);
check("trend header/taskbar (ADR-0007)",html.includes('text(ctx,"Trend"')&&html.includes('"MAX "')&&html.includes('"0s"')&&html.includes("trendTaskY")&&html.includes("ADR-0007"));
check("trend verticals, no grid clutter",!html.includes("setLineDash")&&!html.includes("strokeRect")&&!html.includes("sx=L.statsX"));
check("curve and end dot kept",html.includes("L.plotX+i*(L.plotW-1)/239")&&html.includes("L.plotX+L.plotW-2, py-2"));
if(failures)process.exit(1);console.log("sim/verify.js: ALL CHECKS PASS");
