#!/usr/bin/env node
"use strict";
const fs=require("fs"),path=require("path"),vm=require("vm");
const html=fs.readFileSync(path.join(__dirname,"index.html"),"utf8");
const fonts=fs.readFileSync(path.join(__dirname,"font_data.js"),"utf8");
const source=html.match(/<script>([\s\S]*)<\/script>/)[1];
let failures=0;const check=(name,value)=>{console.log((value?"ok   ":"FAIL ")+name);if(!value)failures++};
const sandbox={console,Math,Uint8ClampedArray,document:undefined};vm.createContext(sandbox);vm.runInContext(fonts+"\n"+source+"\nthis.EXPORTS={UI_W,UI_H,L,X_LABELS,STATUS,traceData,textBitmap,digitBitmap,halfBitmap};",sandbox);
const e=sandbox.EXPORTS;
check("layout width",e.UI_W===960);check("layout height",e.UI_H===320);
check("three regions total",e.L.statusH+e.L.readingH+e.L.trendH===320);
check("reading starts 24",e.L.readingY===24&&e.L.readingH===168);check("trend starts 192",e.L.trendY===192);
check("fixed x labels",JSON.stringify(Array.from(e.X_LABELS))===JSON.stringify(["0.00s","2.50s","5.00s","7.50s","10.00s"]));
const data=e.traceData();check("240 projected columns",data.length===240);check("deterministic non-flat trace",Math.max(...data)>Math.min(...data));
check("authentic labels",["REM","TALK","LSTN","SRQ","TRIG"].every(x=>e.STATUS.includes(x)));
check("no DMM6500 vocabulary",!["DIGITIZE","defbuffer1","No Script","DCCPL"].some(x=>html.includes(x)));
check("simulator-only preset note",html.includes("不代表面板协议"));
check("ohm symbol preset",html.includes("Zin: >10GΩ")&&e.textBitmap("Ω")!=null);
check("digit unit symbols",["µ","°","Ω"].every(c=>e.digitBitmap(c)!=null));
check("half-height font",["D","C","A"].every(c=>e.halfBitmap(c)!=null));
check("left-aligned reading",e.L.readingX===12);
if(failures)process.exit(1);console.log("sim/verify.js: ALL CHECKS PASS");
