#pragma once

#include <stdint.h>

/* Generated by tools/make_digit_font.py - DO NOT EDIT.
 * JetBrains Mono big-digit font: 32x64 px cells, 1bpp, row-packed
 * MSB first (4 bytes/row, 256 bytes per glyph).
 * CHARSET = "0123456789.+-Ee%mukKMWVOhDAC?RFLHzs".
 */

#define FONT_DIGIT_WIDTH 32u
#define FONT_DIGIT_HEIGHT 64u
#define FONT_DIGIT_BYTES_PER_ROW 4u
#define FONT_DIGIT_BYTES_PER_GLYPH 256u
#define FONT_DIGIT_CHAR_COUNT 35u
#define FONT_DIGIT_BASELINE 50u
#define FONT_DIGIT_SYM_MICRO 0u
#define FONT_DIGIT_SYM_DEGREE 1u
#define FONT_DIGIT_SYM_OHM 2u
#define FONT_DIGIT_SYM_COUNT 3u

/* Bitmap for character c (1bpp, MSB first), or NULL if c is not
 * in the charset. The data lives in Flash; the caller does not
 * own it. */
const uint8_t *font_digit_bitmap(char c);

/* Bitmap for one of the FONT_DIGIT_SYM_* symbols, or NULL for an unknown
 * symbol id. Data lives in Flash; the caller does not own it. */
const uint8_t *font_digit_symbol_bitmap(uint8_t sym);

uint16_t font_digit_width(void);
uint16_t font_digit_height(void);
