#!/usr/bin/env python3
"""Rasterize a monospace TTF into 1bpp C arrays for the K2000 small-text font.

Usage:
    python3 tools/make_text_font.py /path/to/DejaVuSansMono.ttf firmware/src KEITHLEY_2000_LCD/Core

Writes font_text.h/font_text.c (12 x 24 px cells, 1bpp, row-packed MSB first
= 2 bytes/row = 48 bytes/glyph) into firmware/src, plus a synced copy under
KEITHLEY_2000_LCD/Core/{Inc,Src} for the CubeMX tree.

Glyphs cover the printable ASCII range 32..126 plus a few non-ASCII DMM
symbols (micro, ohm, degree, plus-minus) exposed through a separate
font_text_symbol_bitmap() interface.

The source TTF is rasterized at SCALE x the cell size with a common baseline
so punctuation and lowercase descenders sit where typography expects them,
thresholded to 1bpp, then box-downsampled to the 12x24 cell.

Re-run the script after any change to CHARSET, SYMBOLS, SCALE, FONT_SIZE,
BASELINE_Y or the source font; the generated files must not be hand-edited.

Requires Pillow:  python3 -m pip install pillow
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

W = 12               # cell width  (px)
H = 24               # cell height (px)
BYTES_PER_ROW = (W + 7) // 8       # 2 (12px does not divide by 8)
SCALE = 4            # supersampling factor for rendering
FONT_SIZE = 82       # source TTF size (at SCALE x)
BASELINE_Y = 72      # shared baseline on the SCALE*H tall canvas
THRESHOLD = 110      # 1bpp cutoff on the antialiased source render

CHARSET = "".join(chr(i) for i in range(32, 127))
SYMBOLS = [("\u00b5", "FONT_TEXT_SYM_MICRO", "micro"),
           ("\u03a9", "FONT_TEXT_SYM_OHM", "ohm"),
           ("\u00b0", "FONT_TEXT_SYM_DEGREE", "degree"),
           ("\u00b1", "FONT_TEXT_SYM_PLUS_MINUS", "plus-minus")]


def make_glyph(font, ch):
    """Return the glyph as a (W x H) 1-bit PIL image."""
    cw, chh = W * SCALE, H * SCALE
    img = Image.new("L", (cw, chh), 0)
    ImageDraw.Draw(img).text((0, BASELINE_Y), ch, font=font, fill=255,
                             anchor="ls")
    img = img.point(lambda p: 255 if p > THRESHOLD else 0)
    img = img.resize((W, H), Image.BOX)
    return img.convert("1", dither=Image.Dither.NONE)


def pack(img):
    """Return the glyph as MSB-first packed bytes (2 bytes/row x 24 rows)."""
    data = img.tobytes()
    if len(data) != BYTES_PER_ROW * H:
        raise SystemExit("packing error: %d bytes, expected %d"
                         % (len(data), BYTES_PER_ROW * H))
    return list(data)


def emit_c(out_dir, cubemx_dir, glyphs, symbol_glyphs):
    header = os.path.join(out_dir, "font_text.h")
    source = os.path.join(out_dir, "font_text.c")

    count = len(CHARSET)
    sym_count = len(SYMBOLS)
    bytes_per_glyph = BYTES_PER_ROW * H

    h_lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        "/* Generated by tools/make_text_font.py - DO NOT EDIT.",
        " * DejaVu Sans Mono small-text font: %dx%d px cells, 1bpp, "
        "row-packed" % (W, H),
        " * MSB first (%d bytes/row, %d bytes per glyph)." % (BYTES_PER_ROW,
                                                              bytes_per_glyph),
        " * Covers printable ASCII %d..%d plus %d DMM symbols." % (32, 126,
                                                                   sym_count),
        " */",
        "",
        "#define FONT_TEXT_WIDTH %du" % W,
        "#define FONT_TEXT_HEIGHT %du" % H,
        "#define FONT_TEXT_BYTES_PER_ROW %du" % BYTES_PER_ROW,
        "#define FONT_TEXT_BYTES_PER_GLYPH %du" % bytes_per_glyph,
        "#define FONT_TEXT_FIRST_CHAR 32u",
        "#define FONT_TEXT_LAST_CHAR 126u",
        "#define FONT_TEXT_CHAR_COUNT %du" % count,
        "",
        "#define FONT_TEXT_SYM_MICRO 0u",
        "#define FONT_TEXT_SYM_OHM 1u",
        "#define FONT_TEXT_SYM_DEGREE 2u",
        "#define FONT_TEXT_SYM_PLUS_MINUS 3u",
        "#define FONT_TEXT_SYM_COUNT %du" % sym_count,
        "",
        "/* Bitmap for ASCII character c (1bpp, MSB first), or NULL for",
        " * characters outside the printable ASCII range. The data lives in",
        " * Flash; the caller does not own it. */",
        "const uint8_t *font_text_bitmap(char c);",
        "",
        "/* Bitmap for one of the FONT_TEXT_SYM_* symbols, or NULL for an",
        " * unknown symbol id. Data lives in Flash; caller does not own it. */",
        "const uint8_t *font_text_symbol_bitmap(uint8_t sym);",
        "",
        "typedef struct {",
        "    const uint8_t *bitmap;",
        "    uint8_t bytes;",
        "} font_text_glyph_t;",
        "",
        "/* Resolve one UTF-8 token to a fixed-cell glyph. Invalid input consumes one",
        " * byte; valid unsupported code points consume their complete token. */",
        "bool font_text_glyph(const char *text, uint8_t length, font_text_glyph_t *glyph);",
        "",
        "uint16_t font_text_width(void);",
        "uint16_t font_text_height(void);",
        "",
    ]
    with open(header, "w") as f:
        f.write("\n".join(h_lines))

    c_lines = ["/* Generated by tools/make_text_font.py - DO NOT EDIT. */",
               '#include "font_text.h"',
               "",
               "static const uint8_t s_text_bitmaps[FONT_TEXT_CHAR_COUNT]"
               "[FONT_TEXT_BYTES_PER_GLYPH] = {"]
    for ch, img in glyphs:
        if ch == " ":
            c_lines.append("    /* space */")
        elif ch == "\\":
            c_lines.append("    /* backslash */")
        elif ch == '"':
            c_lines.append("    /* double quote */")
        elif ch == "'":
            c_lines.append("    /* single quote */")
        else:
            c_lines.append("    /* '%s' */" % ch)
        c_lines.append("    {")
        data = pack(img)
        for row_start in range(0, bytes_per_glyph, 16):
            chunk = data[row_start:row_start + 16]
            c_lines.append("        " + ",".join("0x%02X" % b for b in chunk)
                           + ",")
        c_lines.append("    },")
    c_lines.append("};")
    c_lines.append("")
    c_lines.append("static const uint8_t s_symbol_bitmaps[FONT_TEXT_SYM_COUNT]"
                   "[FONT_TEXT_BYTES_PER_GLYPH] = {")
    for (_, macro, desc), img in zip(SYMBOLS, symbol_glyphs):
        c_lines.append("    /* %s (%s) */" % (macro, desc))
        c_lines.append("    {")
        data = pack(img)
        for row_start in range(0, bytes_per_glyph, 16):
            chunk = data[row_start:row_start + 16]
            c_lines.append("        " + ",".join("0x%02X" % b for b in chunk)
                           + ",")
        c_lines.append("    },")
    c_lines.append("};")
    c_lines.append("")
    c_lines.append("const uint8_t *font_text_bitmap(char c)")
    c_lines.append("{")
    c_lines.append("    uint16_t idx = (uint16_t)(uint8_t)c;")
    c_lines.append("    if (idx < FONT_TEXT_FIRST_CHAR || "
                   "idx > FONT_TEXT_LAST_CHAR) {")
    c_lines.append("        return (const uint8_t *)0;")
    c_lines.append("    }")
    c_lines.append("    return s_text_bitmaps[idx - FONT_TEXT_FIRST_CHAR];")
    c_lines.append("}")
    c_lines.append("")
    c_lines.append("const uint8_t *font_text_symbol_bitmap(uint8_t sym)")
    c_lines.append("{")
    c_lines.append("    if (sym >= FONT_TEXT_SYM_COUNT) {")
    c_lines.append("        return (const uint8_t *)0;")
    c_lines.append("    }")
    c_lines.append("    return s_symbol_bitmaps[sym];")
    c_lines.append("}")
    c_lines.append("")
    c_lines.extend([
        "bool font_text_glyph(const char *text, uint8_t length, font_text_glyph_t *glyph)",
        "{",
        "    const uint8_t *p = (const uint8_t *)text;",
        "    uint32_t cp;",
        "    uint8_t need;",
        "    uint8_t i;",
        "    if (p == 0 || length == 0u || glyph == 0) return false;",
        "    glyph->bitmap = font_text_bitmap((char)p[0]);",
        "    glyph->bytes = 1u;",
        "    if (p[0] <= 0x7Fu) {",
        "        if (glyph->bitmap == 0) glyph->bitmap = font_text_bitmap('?');",
        "        return true;",
        "    }",
        "    if (p[0] >= 0xC2u && p[0] <= 0xDFu) { need = 2u; cp = p[0] & 0x1Fu; }",
        "    else if (p[0] >= 0xE0u && p[0] <= 0xEFu) { need = 3u; cp = p[0] & 0x0Fu; }",
        "    else if (p[0] >= 0xF0u && p[0] <= 0xF4u) { need = 4u; cp = p[0] & 0x07u; }",
        "    else { glyph->bitmap = font_text_bitmap('?'); return true; }",
        "    if (length < need) { glyph->bitmap = font_text_bitmap('?'); return true; }",
        "    for (i = 1u; i < need; i++) {",
        "        if (p[i] < 0x80u || p[i] > 0xBFu) { glyph->bitmap = font_text_bitmap('?'); return true; }",
        "        cp = (cp << 6) | (uint32_t)(p[i] & 0x3Fu);",
        "    }",
        "    if ((need == 3u && cp < 0x800u) || (need == 4u && cp < 0x10000u) ||",
        "        (cp >= 0xD800u && cp <= 0xDFFFu) || cp > 0x10FFFFu) {",
        "        glyph->bitmap = font_text_bitmap('?'); return true;",
        "    }",
        "    glyph->bytes = need;",
        "    if (cp == 0xB5u) glyph->bitmap = font_text_symbol_bitmap(FONT_TEXT_SYM_MICRO);",
        "    else if (cp == 0xB0u) glyph->bitmap = font_text_symbol_bitmap(FONT_TEXT_SYM_DEGREE);",
        "    else if (cp == 0xB1u) glyph->bitmap = font_text_symbol_bitmap(FONT_TEXT_SYM_PLUS_MINUS);",
        "    else if (cp == 0x3A9u) glyph->bitmap = font_text_symbol_bitmap(FONT_TEXT_SYM_OHM);",
        "    else glyph->bitmap = font_text_bitmap('?');",
        "    return true;",
        "}",
        "",
    ])
    c_lines.append("uint16_t font_text_width(void)")
    c_lines.append("{")
    c_lines.append("    return FONT_TEXT_WIDTH;")
    c_lines.append("}")
    c_lines.append("")
    c_lines.append("uint16_t font_text_height(void)")
    c_lines.append("{")
    c_lines.append("    return FONT_TEXT_HEIGHT;")
    c_lines.append("}")
    c_lines.append("")
    with open(source, "w") as f:
        f.write("\n".join(c_lines))

    if cubemx_dir:
        os.makedirs(os.path.join(cubemx_dir, "Inc"), exist_ok=True)
        os.makedirs(os.path.join(cubemx_dir, "Src"), exist_ok=True)
        with open(os.path.join(cubemx_dir, "Inc", "font_text.h"), "w") as f:
            f.write("\n".join(h_lines))
        with open(os.path.join(cubemx_dir, "Src", "font_text.c"), "w") as f:
            f.write("\n".join(c_lines))

    return count, sym_count, bytes_per_glyph


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    ttf, out_dir, cubemx_dir = sys.argv[1], sys.argv[2], sys.argv[3]
    if not os.path.isfile(ttf):
        sys.exit("font not found: %s" % ttf)
    if not os.path.isdir(out_dir):
        sys.exit("output dir not found: %s" % out_dir)

    font = ImageFont.truetype(ttf, FONT_SIZE)
    glyphs = [(ch, make_glyph(font, ch)) for ch in CHARSET]
    symbol_glyphs = [make_glyph(font, ch) for ch, _, _ in SYMBOLS]
    count, sym_count, bytes_per_glyph = emit_c(out_dir, cubemx_dir, glyphs,
                                               symbol_glyphs)

    print("source font    : %s" % ttf)
    print("cell           : %dx%d px, %d bytes/glyph" % (W, H,
                                                         bytes_per_glyph))
    print("ascii glyphs   : %d (chars %d..%d)" % (count, 32, 126))
    print("symbols        : %d" % sym_count)
    for ch, img in glyphs:
        ink = sum(bin(b).count("1") for b in pack(img))
        if ink == 0 and ch != " ":
            print("WARNING: glyph %r has no ink" % ch)
    print("wrote %s and %s, plus CubeMX copy under %s"
          % (os.path.join(out_dir, "font_text.c"),
             os.path.join(out_dir, "font_text.h"), cubemx_dir))


if __name__ == "__main__":
    main()
