#!/usr/bin/env python3
"""Rasterize a TTF into 1bpp C arrays for the K2000 big-digit font.

Usage:
    python3 tools/make_digit_font.py /path/to/JetBrainsMono-Regular.ttf firmware/src

Writes font_digits.c and font_digits.h (48 x 96 px cells, 1bpp, row-packed
MSB first = 6 bytes/row = 576 bytes/glyph).

JetBrains Mono's advance width is 0.6 em, so at font size 96 a digit is
~58 px wide and would not fit the 48 px cell. The script therefore auto-shrinks
the font until every glyph's ink bounding box fits the cell, then draws each
glyph on a common baseline (digits keep a normal readout look, '.' and '-'
sit low near the baseline) and horizontally centres it.

Re-run the script after any change to CHARSET, W, H or the source font; the
generated files must not be hand-edited.

Requires Pillow:  python3 -m pip install pillow
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

W = 48              # cell width  (px)
H = 96              # cell height (px)
BYTES_PER_ROW = W // 8          # 6
CHARSET = "0123456789.+-Ee%mukKMWVOhDAC"


def fits(font):
    """True if every glyph's ink bounding box fits the cell."""
    for ch in CHARSET:
        left, top, right, bottom = font.getbbox(ch, anchor="ls")
        if right - left > W or bottom - top > H:
            return False
    return True


def pick_font(ttf):
    """Largest font size whose every glyph fits the cell."""
    for size in range(H, 7, -1):
        font = ImageFont.truetype(ttf, size=size)
        if fits(font):
            return font
    raise SystemExit("no font size fits the cell for charset %r" % CHARSET)


def make_glyphs(font):
    """Return (glyphs, baseline_y).

    All glyphs share one baseline (anchor 'ls' origin). The baseline is chosen
    so the union of all ink boxes is vertically centred in the cell; because
    digits dominate that union, short glyphs ('.' '-') stay low, near the
    baseline, as in normal typography.
    """
    ink = {ch: font.getbbox(ch, anchor="ls") for ch in CHARSET}
    min_top = min(b[1] for b in ink.values())
    max_bottom = max(b[3] for b in ink.values())
    baseline_y = (H - (max_bottom - min_top)) // 2 - min_top

    glyphs = []
    for ch in CHARSET:
        left, top, right, bottom = ink[ch]
        width = right - left
        img = Image.new("1", (W, H), 0)
        d = ImageDraw.Draw(img)
        anchor_x = (W - width) // 2 - left
        d.text((anchor_x, baseline_y), ch, font=font, fill=1, anchor="ls")
        glyphs.append((ch, (left, top, right, bottom), img))
    return glyphs, baseline_y


def pack(img):
    """Return the glyph as MSB-first packed bytes.

    Pillow stores mode "1" images one byte per pixel but Image.tobytes()
    packs them 8 pixels/byte, MSB first, one row at a time -- exactly the
    format we need (6 bytes/row x 96 rows = 576 bytes).
    """
    data = img.tobytes()
    if len(data) != W * H // 8:
        raise SystemExit("packing error: %d bytes, expected %d"
                         % (len(data), W * H // 8))
    return list(data)


def emit_c(out_dir, glyphs):
    header = os.path.join(out_dir, "font_digits.h")
    source = os.path.join(out_dir, "font_digits.c")

    count = len(CHARSET)
    bytes_per_glyph = W * H // 8

    h_text = (
        "#pragma once\n"
        "\n"
        "#include <stdint.h>\n"
        "\n"
        "/* Generated by tools/make_digit_font.py - DO NOT EDIT.\n"
        " * JetBrains Mono big-digit font: {W}x{H} px cells, 1bpp, "
        "row-packed\n"
        " * MSB first ({bpr} bytes/row, {bpg} bytes per glyph).\n"
        " * CHARSET = \"{charset}\".\n"
        " */\n"
        "\n"
        "#define FONT_DIGIT_WIDTH {W}u\n"
        "#define FONT_DIGIT_HEIGHT {H}u\n"
        "#define FONT_DIGIT_BYTES_PER_ROW {bpr}u\n"
        "#define FONT_DIGIT_BYTES_PER_GLYPH {bpg}u\n"
        "#define FONT_DIGIT_CHAR_COUNT {count}u\n"
        "\n"
        "/* Bitmap for character c (1bpp, MSB first), or NULL if c is not in\n"
        " * the charset. The data lives in Flash; the caller does not own it. "
        "*/\n"
        "const uint8_t *font_digit_bitmap(char c);\n"
        "\n"
        "uint16_t font_digit_width(void);\n"
        "uint16_t font_digit_height(void);\n"
    ).format(W=W, H=H, bpr=BYTES_PER_ROW, bpg=bytes_per_glyph,
             charset=CHARSET, count=count)
    with open(header, "w") as f:
        f.write(h_text)

    c_lines = []
    c_lines.append("/* Generated by tools/make_digit_font.py - DO NOT EDIT. */")
    c_lines.append('#include "font_digits.h"')
    c_lines.append("")
    c_lines.append("static const uint8_t s_digit_bitmaps[FONT_DIGIT_CHAR_COUNT]"
                   "[FONT_DIGIT_BYTES_PER_GLYPH] = {")
    for ch, _, img in glyphs:
        c_lines.append("    /* '%s' */" % ch)
        c_lines.append("    {")
        data = pack(img)
        for row_start in range(0, bytes_per_glyph, 16):
            chunk = data[row_start:row_start + 16]
            c_lines.append("        " + ",".join("0x%02X" % b for b in chunk)
                           + ",")
        c_lines.append("    },")
    c_lines.append("};")
    c_lines.append("")
    c_lines.append("static const char s_digit_chars[] = \"%s\";" % CHARSET)
    c_lines.append("")
    c_lines.append("const uint8_t *font_digit_bitmap(char c)")
    c_lines.append("{")
    c_lines.append("    uint16_t i;")
    c_lines.append("    for (i = 0u; i < FONT_DIGIT_CHAR_COUNT; i++) {")
    c_lines.append("        if (s_digit_chars[i] == c) {")
    c_lines.append("            return s_digit_bitmaps[i];")
    c_lines.append("        }")
    c_lines.append("    }")
    c_lines.append("    return (const uint8_t *)0;")
    c_lines.append("}")
    c_lines.append("")
    c_lines.append("uint16_t font_digit_width(void)")
    c_lines.append("{")
    c_lines.append("    return FONT_DIGIT_WIDTH;")
    c_lines.append("}")
    c_lines.append("")
    c_lines.append("uint16_t font_digit_height(void)")
    c_lines.append("{")
    c_lines.append("    return FONT_DIGIT_HEIGHT;")
    c_lines.append("}")
    c_lines.append("")
    with open(source, "w") as f:
        f.write("\n".join(c_lines))

    return count, bytes_per_glyph


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    ttf, out_dir = sys.argv[1], sys.argv[2]
    if not os.path.isfile(ttf):
        sys.exit("font not found: %s" % ttf)
    if not os.path.isdir(out_dir):
        sys.exit("output dir not found: %s" % out_dir)

    font = pick_font(ttf)
    glyphs, baseline_y = make_glyphs(font)
    count, bytes_per_glyph = emit_c(out_dir, glyphs)

    print("font size     : %d px" % font.size)
    print("baseline_y    : %d (cell height %d)" % (baseline_y, H))
    print("glyph count   : %d" % count)
    print("bytes/glyph   : %d" % bytes_per_glyph)
    for ch, (left, top, right, bottom), img in glyphs:
        ink = sum(bin(b).count("1") for b in img.tobytes())
        print("  '%s' bbox=(%d,%d,%d,%d) set_bits=%d"
              % (ch, left, top, right, bottom, ink))
    print("wrote %s and %s" % (os.path.join(out_dir, "font_digits.c"),
                               os.path.join(out_dir, "font_digits.h")))


if __name__ == "__main__":
    main()
