#!/usr/bin/env python3
"""Extract the firmware font bitmaps into a JS data file for the HTML layout
simulator (sim/index.html). Reads font_digits.c / font_text.c and emits
sim/font_data.js with the same 1bpp row-packed MSB-first byte arrays, so the
simulator renders glyphs bit-for-bit like the firmware.

Usage:
    python3 tools/make_sim_font.py firmware/src sim/font_data.js
"""
import os
import re
import sys


def parse_bitmaps(path):
    """Return list of glyph byte-lists from a C `static const uint8_t name[N][M] = { ... }` block."""
    with open(path, "r", encoding="utf-8") as fh:
        src = fh.read()
    m = re.search(r"=\s*\{(.*?)\n\};", src, re.S)
    if not m:
        raise SystemExit(f"no bitmap array found in {path}")
    body = m.group(1)
    glyphs = []
    for glyph in re.finditer(r"\{\s*(.*?)\s*\}", body, re.S):
        bytes_ = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", glyph.group(1))]
        if bytes_:
            glyphs.append(bytes_)
    return glyphs


def digits_js():
    glyphs = parse_bitmaps(sys.argv[1] + "/font_digits.c")
    chars = "0123456789.+-Ee%mukKMWVOhDAC?RFL"
    return ("const DIGIT_CHARS = %r;\n" % chars) + \
        "const DIGIT_W = 48, DIGIT_H = 96, DIGIT_BPR = 6;\n" + \
        "const DIGIT_BITMAPS = [\n" + ",\n".join("  [" + ",".join("0x%02X" % b for b in g) + "]" for g in glyphs) + "\n];\n"


def text_js():
    glyphs = parse_bitmaps(sys.argv[1] + "/font_text.c")
    # font_text.c order: 95 printable ASCII (32..126) then 4 symbols.
    ascii_glyphs = glyphs[:95]
    sym_glyphs = glyphs[95:]
    out = ["const TEXT_FIRST = 32, TEXT_LAST = 126;",
           "const TEXT_W = 12, TEXT_H = 24, TEXT_BPR = 2;",
           "const TEXT_BITMAPS = ["]
    for g in ascii_glyphs:
        out.append("  [" + ",".join("0x%02X" % b for b in g) + "],")
    out.append("];")
    out.append("const SYMBOL_BITMAPS = [")
    for g in sym_glyphs:
        out.append("  [" + ",".join("0x%02X" % b for b in g) + "],")
    out.append("];")
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    out_path = sys.argv[2]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/make_sim_font.py - DO NOT EDIT.\n")
        fh.write("// Font bitmaps extracted from firmware/src; identical bytes to the C arrays.\n\n")
        fh.write(digits_js())
        fh.write("\n")
        fh.write(text_js())
    print(f"wrote {out_path}: "
          f"{len(re.findall(r'0x', open(out_path).read()))} bytes")


if __name__ == "__main__":
    main()