#!/usr/bin/env python3
"""Extract the firmware font bitmaps into a JS data file for the HTML layout
simulator (sim/index.html). Reads font_digits.c / font_half.c / font_text.c
and emits sim/font_data.js with the same 1bpp row-packed MSB-first byte
arrays, so the simulator renders glyphs bit-for-bit like the firmware.

Usage:
    python3 tools/make_sim_font.py firmware/src sim/font_data.js
"""
import os
import re
import sys


def parse_bitmaps(path):
    """Return list of glyph byte-lists from a C `static const uint8_t name[N][M] = { ... }` block."""
    with open(path, "r", encoding="utf-8") as fh:
        src = fh.read()
    arrays = re.findall(r"=\s*\{(.*?)\n\};", src, re.S)
    if not arrays:
        raise SystemExit(f"no bitmap array found in {path}")
    glyphs = []
    for body in arrays:
        for glyph in re.finditer(r"\{\s*(.*?)\s*\}", body, re.S):
            bytes_ = [int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", glyph.group(1))]
            if bytes_:
                glyphs.append(bytes_)
    return glyphs


def read_dim(name, header_path):
    """Pull WIDTH/HEIGHT/BYTES_PER_ROW from the generated .h."""
    with open(header_path, "r", encoding="utf-8") as fh:
        src = fh.read()
    w = int(re.search(r"#define %s_WIDTH (\d+)u" % name, src).group(1))
    h = int(re.search(r"#define %s_HEIGHT (\d+)u" % name, src).group(1))
    bpr = int(re.search(r"#define %s_BYTES_PER_ROW (\d+)u" % name, src).group(1))
    return w, h, bpr


def emit_array(var, glyphs, indent="  "):
    return ",\n".join(indent + "[" + ",".join("0x%02X" % b for b in g) + "]"
                      for g in glyphs)


def digits_js(src_dir):
    glyphs = parse_bitmaps(src_dir + "/font_digits.c")
    w, h, bpr = read_dim("FONT_DIGIT", src_dir + "/font_digits.h")
    chars = re.search(r's_digit_chars\[\] = "([^"]*)"',
                      open(src_dir + "/font_digits.c", encoding="utf-8").read()).group(1)
    ascii_n = len(chars)
    sym_n = len(glyphs) - ascii_n
    ascii_glyphs = glyphs[:ascii_n]
    sym_glyphs = glyphs[ascii_n:]
    out = []
    out.append("const DIGIT_CHARS = %r;" % chars)
    out.append("const DIGIT_W = %d, DIGIT_H = %d, DIGIT_BPR = %d;" % (w, h, bpr))
    out.append("const DIGIT_BITMAPS = [")
    out.append(emit_array("d", ascii_glyphs) + ",")
    out.append("];")
    out.append("const DIGIT_SYMBOL_BITMAPS = [")
    out.append(emit_array("ds", sym_glyphs) + ",")
    out.append("];")
    return "\n".join(out)


def half_js(src_dir):
    glyphs = parse_bitmaps(src_dir + "/font_half.c")
    w, h, bpr = read_dim("FONT_HALF", src_dir + "/font_half.h")
    chars = re.search(r's_half_chars\[\] = "([^"]*)"',
                      open(src_dir + "/font_half.c", encoding="utf-8").read()).group(1)
    out = []
    out.append("const HALF_CHARS = %r;" % chars)
    out.append("const HALF_W = %d, HALF_H = %d, HALF_BPR = %d;" % (w, h, bpr))
    out.append("const HALF_BITMAPS = [")
    out.append(emit_array("hf", glyphs) + ",")
    out.append("];")
    return "\n".join(out)


def text_js(src_dir):
    glyphs = parse_bitmaps(src_dir + "/font_text.c")
    # font_text.c order: 95 printable ASCII (32..126) then 4 symbols.
    ascii_glyphs = glyphs[:95]
    sym_glyphs = glyphs[95:]
    out = ["const TEXT_FIRST = 32, TEXT_LAST = 126;",
           "const TEXT_W = 12, TEXT_H = 24, TEXT_BPR = 2;",
           "const TEXT_BITMAPS = ["]
    for g in ascii_glyphs:
        out.append("  [" + ",".join("0x%02X" % b for b in g) + "],")
    out.append("];")
    out.append("const SYMBOL_BITMAPS = [")
    for g in sym_glyphs:
        out.append("  [" + ",".join("0x%02X" % b for b in g) + "],")
    out.append("];")
    return "\n".join(out)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    src_dir, out_path = sys.argv[1], sys.argv[2]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/make_sim_font.py - DO NOT EDIT.\n")
        fh.write("// Font bitmaps extracted from firmware/src; identical bytes to the C arrays.\n\n")
        fh.write(digits_js(src_dir))
        fh.write("\n\n")
        fh.write(half_js(src_dir))
        fh.write("\n\n")
        fh.write(text_js(src_dir))
    total = len(re.findall(r'0x', open(out_path, encoding="utf-8").read()))
    chars = re.search(r"DIGIT_CHARS = '([^']*)'",
                      open(out_path, encoding="utf-8").read()).group(1)
    half_chars = re.search(r"HALF_CHARS = '([^']*)'",
                           open(out_path, encoding="utf-8").read()).group(1)
    print(f"wrote {out_path}: {total} bytes")
    print(f"  digits: {len(chars)} chars, half: {len(half_chars)} chars")


if __name__ == "__main__":
    main()