#pragma once

#include <stdint.h>

/* Generated by tools/make_text_font.py - DO NOT EDIT.
 * DejaVu Sans Mono small-text font: 12x24 px cells, 1bpp, row-packed
 * MSB first (2 bytes/row, 48 bytes per glyph).
 * Covers printable ASCII 32..126 plus 4 DMM symbols.
 */

#define FONT_TEXT_WIDTH 12u
#define FONT_TEXT_HEIGHT 24u
#define FONT_TEXT_BYTES_PER_ROW 2u
#define FONT_TEXT_BYTES_PER_GLYPH 48u
#define FONT_TEXT_FIRST_CHAR 32u
#define FONT_TEXT_LAST_CHAR 126u
#define FONT_TEXT_CHAR_COUNT 95u

#define FONT_TEXT_SYM_MICRO 0u
#define FONT_TEXT_SYM_OHM 1u
#define FONT_TEXT_SYM_DEGREE 2u
#define FONT_TEXT_SYM_PLUS_MINUS 3u
#define FONT_TEXT_SYM_COUNT 4u

/* Bitmap for ASCII character c (1bpp, MSB first), or NULL for
 * characters outside the printable ASCII range. The data lives in
 * Flash; the caller does not own it. */
const uint8_t *font_text_bitmap(char c);

/* Bitmap for one of the FONT_TEXT_SYM_* symbols, or NULL for an
 * unknown symbol id. Data lives in Flash; caller does not own it. */
const uint8_t *font_text_symbol_bitmap(uint8_t sym);

uint16_t font_text_width(void);
uint16_t font_text_height(void);
