#pragma once

#include <stdint.h>

/* Generated by tools/make_digit_font.py - DO NOT EDIT.
 * JetBrains Mono big-digit font: 32x64 px cells, 1bpp, row-packed
 * MSB first (4 bytes/row, 256 bytes per glyph).
 * CHARSET = "DCA".
 */

#define FONT_HALF_WIDTH 32u
#define FONT_HALF_HEIGHT 64u
#define FONT_HALF_BYTES_PER_ROW 4u
#define FONT_HALF_BYTES_PER_GLYPH 256u
#define FONT_HALF_CHAR_COUNT 3u
#define FONT_HALF_SYM_COUNT 3u
#define FONT_HALF_BASELINE 51u


/* Bitmap for character c (1bpp, MSB first), or NULL if c is not
 * in the charset. The data lives in Flash; the caller does not
 * own it. */
const uint8_t *font_half_bitmap(char c);

uint16_t font_half_width(void);
uint16_t font_half_height(void);
