#pragma once

#include <stdint.h>

/* Generated by tools/make_digit_font.py - DO NOT EDIT.
 * JetBrains Mono big-digit font: 48x96 px cells, 1bpp, row-packed
 * MSB first (6 bytes/row, 576 bytes per glyph).
 * CHARSET = "0123456789.+-Ee%mukKMWVOhDAC?RFL".
 */

#define FONT_DIGIT_WIDTH 48u
#define FONT_DIGIT_HEIGHT 96u
#define FONT_DIGIT_BYTES_PER_ROW 6u
#define FONT_DIGIT_BYTES_PER_GLYPH 576u
#define FONT_DIGIT_CHAR_COUNT 32u

/* Bitmap for character c (1bpp, MSB first), or NULL if c is not in
 * the charset. The data lives in Flash; the caller does not own it. */
const uint8_t *font_digit_bitmap(char c);

uint16_t font_digit_width(void);
uint16_t font_digit_height(void);
